# Main Alacritty Config File

# Import other config files
import = ['~/.config/alacritty/colors.toml']

# Set Fish Shell
shell = '/bin/fish'

# Font Config
[font]
normal.family = 'SFMono'
bold.family = 'SFMono'
italic.family = 'SFMono'
bold_italic.family = 'SFMono'
